
import type { Equal, Expect } from '@type-challenges/utils';
import type { Boolean, Not, Or, And, Xor } from '../../index';

export type Cases = [
	Expect<Equal<Boolean<true> ,  true>>,
	Expect<Equal<Boolean<false> ,  false>>,
	Expect<Equal<Boolean<''> ,  false>>,
	Expect<Equal<Boolean<0> ,  false>>,
	Expect<Equal<Boolean<undefined> ,  false>>,
	Expect<Equal<Boolean<null> ,  false>>,
	Expect<Equal<Boolean<1> ,  true>>,
	Expect<Equal<Boolean<'0'> ,  true>>,
	Expect<Equal<Boolean<{}> ,  true>>,
	Expect<Equal<Boolean<[]> ,  true>>,
	Expect<Equal<Boolean<boolean> ,  boolean>>,
	Expect<Equal<Boolean<number> ,  boolean>>,
	Expect<Equal<Boolean<string> ,  boolean>>,
	Expect<Equal<Boolean<object> ,  true>>,
	Expect<Equal<Boolean<unknown[]> ,  true>>,
	Expect<Equal<Not<true> ,  false>>,
	Expect<Equal<Not<false> ,  true>>,
	Expect<Equal<Not<boolean> ,  never>>,
	Expect<Equal<Or<true, true> ,  true>>,
	Expect<Equal<Or<true, false> ,  true>>,
	Expect<Equal<Or<false, true> ,  true>>,
	Expect<Equal<Or<false, false> ,  false>>,
	Expect<Equal<Or<[true, true, true]> ,  true>>,
	Expect<Equal<Or<[false, true, false]> ,  true>>,
	Expect<Equal<Or<[false, false, false]> ,  false>>,
	Expect<Equal<Or<boolean, true> ,  never>>,
	Expect<Equal<And<true, true> ,  true>>,
	Expect<Equal<And<true, false> ,  false>>,
	Expect<Equal<And<false, true> ,  false>>,
	Expect<Equal<And<false, false> ,  false>>,
	Expect<Equal<And<[true, true, true]> ,  true>>,
	Expect<Equal<And<[false, true, false]> ,  false>>,
	Expect<Equal<And<[false, false, false]> ,  false>>,
	Expect<Equal<And<boolean, true> ,  never>>,
	Expect<Equal<Xor<true, true> ,  true>>,
	Expect<Equal<Xor<true, false> ,  false>>,
	Expect<Equal<Xor<false, true> ,  false>>,
	Expect<Equal<Xor<false, false> ,  true>>,
	Expect<Equal<Xor<[true, true, true]> ,  true>>,
	Expect<Equal<Xor<[false, true, false]> ,  true>>,
	Expect<Equal<Xor<[false, false, false]> ,  false>>,
	Expect<Equal<Xor<boolean, true> ,  never>>
];
			